### ISSUE TITLE
Version 0.1 checklist

### ISSUE THREAD

**Issue by sthenic** [sthenic/sigscape#2]
- [x] Error propagation via thread messages
- [x] Add 'dirty' parameter state, i.e. unapplied changes
  - We probably need to add a 'button state' for every button in the command palette
- [x] Remove parameter window
- [x] ~~Remove `ADQR_` error space, just use the one from the ADQAPI~~
- [x] "Scale to input range/0 dBFS"-buttons
- [x] FFT horizontal values in frequency
- [x] Time domain vertical values in millivolts
- [x] FFT tone annotations
- [x] FFT windowing
- [x] ~~Max/min tracking horizontal lines (persistent)~~
- [x] ~Large strides when the plot contains more than say 32k samples~
  - Probably need to be able to opt out from this.
- [x] Shortcut command buttons 
  - [x] Records with 64k samples from all channels, periodic trigger.
  - [x] Internal reference
  - [x] External reference 10 MHz
  - [x] External clock
- [x] Time domain markers
  - [x] Add and reposition
  - [x] X & Y labels
  - [x] Add to time domain metrics (deltas, frequency etc.)
  - [x] ~~Add frequency conversion~~  #8
- [x] Frequency domain markers
  - [x] Add to metrics
- [x] Add new FFT metrics:
  - [x] Length
  - [x] Bin range
- [x] Modal confirmation when initializing parameters if a file already exists.
- [x] Mute/solo for channel
- [x] Percentage of full scale etc.
- [x] Scatter plot w/ time lag
- [x] ~~Trigger point annotation? Implied at 0?~~
- [x] Show units per divison
- [x] ~~Waveform memory?~~  #8
- [x] Figure out default file storage
- [x] Saving to file
  - [x] Waveform data
  - [x] Plot
- [x] ~Launch editor?~
- [x] Temperatures from Sysman
- [x] Indication when there's no data
- [x] Scaling in plot when channels have different input ranges
- [x] Plotting/storing in ADC codes
  - [x] Move query & formatting functions into the record type
- [x] Header status, like overrange, FIFO fill etc?
- [x] Update README
- [x] `#pragma once`
- [x] Embed the version number
- [x] ~~Limit data rate?~~  #8
- [x] ~~File dialog clears filename on directory navigation~~
- [x] Copy metrics to clipboard (CSV?)
- [x] ADQAPI version validation + popup
- [x] Add energy scaled windowing ([RMS](https://dsp.stackexchange.com/questions/85277/what-is-the-energycorrection-or-amplitude-correction-for-a-tukey-window))
- [x] Plot toggle for energy/amplitude scaling
  - [x] Annotations should follow the plot toggle so we need to separate the coordinates and values
- [x] Show NPSD instead of the "noise average": just divide by the bin size. Unit `dBFS/Hz`.
- [x] Rename "IEEE ENOB" to something like "ENOB relative to full-scale" or "Full-scale ENOB".
- [x] Send all the processing options in a message instead of one by one.
- [x] FFT averaging (needs reset capabilities)
- [x] ~~Max hold (maximum for each bin in the FFT)~~ #8
- [x] Standard deviation (`sdev`)
- [x] Try to detect thunderbolt plug-and-play events: 
  - [x] Windows: https://learn.microsoft.com/en-us/windows/win32/devio/wm-devicechange or https://learn.microsoft.com/en-us/windows/win32/api/cfgmgr32/nf-cfgmgr32-cm_register_notification
    - GUID: `46c58a4e-05fb-441e-84f5-55aa37e4b412`
    - Thunderbolt events seem finicky, can we poll using https://learn.microsoft.com/en-us/windows/win32/api/cfgmgr32/nf-cfgmgr32-cm_get_device_interface_lista?
  - [x] Linux: use `libudev`
    - http://cholla.mmto.org/computers/usb/OLD/tutorial_usbloger.html
    - May need polling here too? With some filtering for 
      - `udev_device_get_sysattr_value(device, "subsystem_vendor") == "0x1b37"`
      - `udev_device_get_sysattr_value(device, "vendor") == "0x1b37"`
-  [x] Clean up `printf`
